### ISSUE TITLE
Remove dependency on Pkg

### ISSUE THREAD

**Issue by giordano** [Herb-AI/Herb.jl#100]
I think there are two problems here:

* the main package requires `Pkg`: https://github.com/Herb-AI/Herb.jl/blob/13e8b88f7444391cf603a5bf53424448321b281f/Project.toml#L13 while [not using it anywhere in the source code](https://github.com/search?q=repo%3AHerb-AI%2FHerb.jl+Pkg+path%3A%2F^src\%2F%2F&type=code).  This should be solved by just removing that line in `Project.toml`
* the tests use `Pkg` to run the tests of upstream packages: https://github.com/Herb-AI/Herb.jl/blob/13e8b88f7444391cf603a5bf53424448321b281f/test/runtests.jl#L15-L26  This package looks like a metapackage which pulls together multiple packages, which is fine, but I'm not sure just running upstream packages test is a good approach, since they are already tested individually.  Can there be integration tests, for example based on the [tutorials in the docs](https://herb-ai.github.io/Herb.jl/dev/), to make sure they keep working?

**Comment by ReubenJ** [comment]
Thanks for the suggestion, @giordano! Removing the dependency on `Pkg` definitely makes sense. I had started adding workflows for doctests to the individual repositories in #63, and I could also see doctests on the tutorials replacing the individual package tests in this meta package. If it's as easy as copying similar changes over from what I was working on in #63, I can get this updated soon. Otherwise, we'll put it on our to-do list to address soon.

Thanks again for the suggestion!
